name: Build & Deploy Backend to Azure App Service

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t toms1/flask-healthcheck-backend:latest ./backend

      - name: Push to Docker Hub
        run: docker push toms1/flask-healthcheck-backend:latest

      - name: Azure Web App Deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'app-healthcheck-demo'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'toms1/flask-healthcheck-backend:latest'
